# Generated by Django 5.2.7 on 2025-10-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='heading',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
