# Generated by Django 5.2.7 on 2025-10-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='heading',
        ),
    ]
