# Generated by Django 5.2.7 on 2025-11-11 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_category_rename_date_expense_entry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Student Living', 'Student Living'), ('Mix', 'Mix'), ('PG', 'PG')], max_length=50)),
                ('tenant_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], max_length=20)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Inactive', 'Inactive')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('occupied_beds', models.PositiveIntegerField(default=0)),
                ('rent_per_bed', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='expenses.property')),
            ],
        ),
    ]
