# Generated by Django 5.2.7 on 2025-11-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_property_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='property',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.property'),
        ),
    ]
