# Generated by Django 5.2.7 on 2025-11-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_expense_category_alter_expense_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
