# Generated by Django 5.2.7 on 2025-11-19 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='rent',
            name='bill_upload',
            field=models.FileField(blank=True, null=True, upload_to='rent_bills/'),
        ),
        migrations.AddField(
            model_name='rent',
            name='billing_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='rent_cycle',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='utr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Card', 'Card'), ('NetBanking', 'NetBanking'), ('Wallet', 'Wallet'), ('Cash', 'Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tenant_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
