# Generated by Django 5.2.7 on 2025-11-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('tenant_phone', models.CharField(max_length=15)),
                ('tenant_email', models.EmailField(max_length=254, unique=True)),
                ('property_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
